// Static NSE stock list for offline search. Symbols use Yahoo Finance format (SYMBOL.NS).
export const NSE_STOCKS = [
  // ── Nifty 50 ─────────────────────────────────────────
  { symbol: "RELIANCE.NS",    name: "Reliance Industries" },
  { symbol: "TCS.NS",         name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK.NS",    name: "HDFC Bank" },
  { symbol: "INFY.NS",        name: "Infosys" },
  { symbol: "ICICIBANK.NS",   name: "ICICI Bank" },
  { symbol: "HINDUNILVR.NS",  name: "Hindustan Unilever" },
  { symbol: "KOTAKBANK.NS",   name: "Kotak Mahindra Bank" },
  { symbol: "SBIN.NS",        name: "State Bank of India" },
  { symbol: "BHARTIARTL.NS",  name: "Bharti Airtel" },
  { symbol: "AXISBANK.NS",    name: "Axis Bank" },
  { symbol: "BAJFINANCE.NS",  name: "Bajaj Finance" },
  { symbol: "WIPRO.NS",       name: "Wipro" },
  { symbol: "ITC.NS",         name: "ITC" },
  { symbol: "ASIANPAINT.NS",  name: "Asian Paints" },
  { symbol: "MARUTI.NS",      name: "Maruti Suzuki" },
  { symbol: "ULTRACEMCO.NS",  name: "UltraTech Cement" },
  { symbol: "SUNPHARMA.NS",   name: "Sun Pharmaceutical" },
  { symbol: "TECHM.NS",       name: "Tech Mahindra" },
  { symbol: "NTPC.NS",        name: "NTPC" },
  { symbol: "LT.NS",          name: "Larsen & Toubro" },
  { symbol: "POWERGRID.NS",   name: "Power Grid Corporation" },
  { symbol: "M&M.NS",         name: "Mahindra & Mahindra" },
  { symbol: "TITAN.NS",       name: "Titan Company" },
  { symbol: "NESTLEIND.NS",   name: "Nestle India" },
  { symbol: "BAJAJFINSV.NS",  name: "Bajaj Finserv" },
  { symbol: "TATAMOTORS.NS",  name: "Tata Motors" },
  { symbol: "HCLTECH.NS",     name: "HCL Technologies" },
  { symbol: "DRREDDY.NS",     name: "Dr. Reddy's Laboratories" },
  { symbol: "ONGC.NS",        name: "Oil & Natural Gas Corporation" },
  { symbol: "COALINDIA.NS",   name: "Coal India" },
  { symbol: "JSWSTEEL.NS",    name: "JSW Steel" },
  { symbol: "TATASTEEL.NS",   name: "Tata Steel" },
  { symbol: "GRASIM.NS",      name: "Grasim Industries" },
  { symbol: "HINDALCO.NS",    name: "Hindalco Industries" },
  { symbol: "SBILIFE.NS",     name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE.NS",    name: "HDFC Life Insurance" },
  { symbol: "DIVISLAB.NS",    name: "Divi's Laboratories" },
  { symbol: "BPCL.NS",        name: "Bharat Petroleum" },
  { symbol: "CIPLA.NS",       name: "Cipla" },
  { symbol: "EICHERMOT.NS",   name: "Eicher Motors" },
  { symbol: "BAJAJ-AUTO.NS",  name: "Bajaj Auto" },
  { symbol: "HEROMOTOCO.NS",  name: "Hero MotoCorp" },
  { symbol: "BRITANNIA.NS",   name: "Britannia Industries" },
  { symbol: "TATACONSUM.NS",  name: "Tata Consumer Products" },
  { symbol: "APOLLOHOSP.NS",  name: "Apollo Hospitals" },
  { symbol: "ADANIENT.NS",    name: "Adani Enterprises" },
  { symbol: "ADANIPORTS.NS",  name: "Adani Ports" },
  { symbol: "INDUSINDBK.NS",  name: "IndusInd Bank" },
  { symbol: "UPL.NS",         name: "UPL" },
  { symbol: "SHREECEM.NS",    name: "Shree Cement" },

  // ── Nifty Next 50 / Large Cap ─────────────────────────
  { symbol: "ADANIGREEN.NS",  name: "Adani Green Energy" },
  { symbol: "ADANIPOWER.NS",  name: "Adani Power" },
  { symbol: "AMBUJACEM.NS",   name: "Ambuja Cements" },
  { symbol: "ACC.NS",         name: "ACC" },
  { symbol: "AUROPHARMA.NS",  name: "Aurobindo Pharma" },
  { symbol: "BANDHANBNK.NS",  name: "Bandhan Bank" },
  { symbol: "BERGEPAINT.NS",  name: "Berger Paints" },
  { symbol: "BIOCON.NS",      name: "Biocon" },
  { symbol: "BOSCHLTD.NS",    name: "Bosch" },
  { symbol: "CHOLAFIN.NS",    name: "Cholamandalam Investment" },
  { symbol: "COLPAL.NS",      name: "Colgate-Palmolive India" },
  { symbol: "CONCOR.NS",      name: "Container Corporation of India" },
  { symbol: "DABUR.NS",       name: "Dabur India" },
  { symbol: "DLF.NS",         name: "DLF" },
  { symbol: "DMART.NS",       name: "Avenue Supermarts (D-Mart)" },
  { symbol: "GAIL.NS",        name: "GAIL India" },
  { symbol: "GODREJCP.NS",    name: "Godrej Consumer Products" },
  { symbol: "HAVELLS.NS",     name: "Havells India" },
  { symbol: "HDFCAMC.NS",     name: "HDFC Asset Management" },
  { symbol: "HINDPETRO.NS",   name: "Hindustan Petroleum" },
  { symbol: "IOC.NS",         name: "Indian Oil Corporation" },
  { symbol: "IRCTC.NS",       name: "Indian Railway Catering & Tourism" },
  { symbol: "LTIM.NS",        name: "LTIMindtree" },
  { symbol: "LTTS.NS",        name: "L&T Technology Services" },
  { symbol: "LUPIN.NS",       name: "Lupin" },
  { symbol: "MARICO.NS",      name: "Marico" },
  { symbol: "MRF.NS",         name: "MRF" },
  { symbol: "MUTHOOTFIN.NS",  name: "Muthoot Finance" },
  { symbol: "NMDC.NS",        name: "NMDC" },
  { symbol: "NAUKRI.NS",      name: "Info Edge (Naukri.com)" },
  { symbol: "OFSS.NS",        name: "Oracle Financial Services" },
  { symbol: "PAGEIND.NS",     name: "Page Industries (Jockey)" },
  { symbol: "PIDILITIND.NS",  name: "Pidilite Industries" },
  { symbol: "POLYCAB.NS",     name: "Polycab India" },
  { symbol: "PVRINOX.NS",     name: "PVR Inox" },
  { symbol: "SAIL.NS",        name: "Steel Authority of India" },
  { symbol: "SIEMENS.NS",     name: "Siemens" },
  { symbol: "TATACOMM.NS",    name: "Tata Communications" },
  { symbol: "TORNTPHARM.NS",  name: "Torrent Pharmaceuticals" },
  { symbol: "TRENT.NS",       name: "Trent" },
  { symbol: "TVSMOTORS.NS",   name: "TVS Motor Company" },
  { symbol: "VEDL.NS",        name: "Vedanta" },
  { symbol: "ZOMATO.NS",      name: "Zomato" },
  { symbol: "PNB.NS",         name: "Punjab National Bank" },
  { symbol: "BANKBARODA.NS",  name: "Bank of Baroda" },
  { symbol: "CANBK.NS",       name: "Canara Bank" },

  // ── Midcap & Popular Stocks ───────────────────────────
  { symbol: "ABFRL.NS",       name: "Aditya Birla Fashion & Retail" },
  { symbol: "ABB.NS",         name: "ABB India" },
  { symbol: "ALKEM.NS",       name: "Alkem Laboratories" },
  { symbol: "ANGELONE.NS",    name: "Angel One" },
  { symbol: "APOLLOTYRE.NS",  name: "Apollo Tyres" },
  { symbol: "ASTRAL.NS",      name: "Astral" },
  { symbol: "ATUL.NS",        name: "Atul" },
  { symbol: "AUBANK.NS",      name: "AU Small Finance Bank" },
  { symbol: "BALKRISIND.NS",  name: "Balkrishna Industries" },
  { symbol: "BEL.NS",         name: "Bharat Electronics" },
  { symbol: "BHEL.NS",        name: "Bharat Heavy Electricals" },
  { symbol: "BLUEDART.NS",    name: "Blue Dart Express" },
  { symbol: "BLUESTARCO.NS",  name: "Blue Star" },
  { symbol: "BRIGADE.NS",     name: "Brigade Enterprises" },
  { symbol: "BSE.NS",         name: "BSE Limited" },
  { symbol: "CEATLTD.NS",     name: "CEAT" },
  { symbol: "CESC.NS",        name: "CESC" },
  { symbol: "COFORGE.NS",     name: "Coforge" },
  { symbol: "CROMPTON.NS",    name: "Crompton Greaves Consumer" },
  { symbol: "CUMMINSIND.NS",  name: "Cummins India" },
  { symbol: "CYIENT.NS",      name: "Cyient" },
  { symbol: "DALMIACEMEN.NS", name: "Dalmia Bharat" },
  { symbol: "DCBBANK.NS",     name: "DCB Bank" },
  { symbol: "DEEPAKNTR.NS",   name: "Deepak Nitrite" },
  { symbol: "DELHIVERY.NS",   name: "Delhivery" },
  { symbol: "DEVYANI.NS",     name: "Devyani International" },
  { symbol: "DIXON.NS",       name: "Dixon Technologies" },
  { symbol: "EMAMILTD.NS",    name: "Emami" },
  { symbol: "ENGINERSIN.NS",  name: "Engineers India" },
  { symbol: "EQUITASBNK.NS",  name: "Equitas Small Finance Bank" },
  { symbol: "EXIDEIND.NS",    name: "Exide Industries" },
  { symbol: "FEDERALBNK.NS",  name: "Federal Bank" },
  { symbol: "FINEORG.NS",     name: "Fine Organic Industries" },
  { symbol: "FORTIS.NS",      name: "Fortis Healthcare" },
  { symbol: "GLAND.NS",       name: "Gland Pharma" },
  { symbol: "GLENMARK.NS",    name: "Glenmark Pharmaceuticals" },
  { symbol: "GMRINFRA.NS",    name: "GMR Airports Infrastructure" },
  { symbol: "GODREJPROP.NS",  name: "Godrej Properties" },
  { symbol: "GSPL.NS",        name: "Gujarat State Petronet" },
  { symbol: "GUJGASLTD.NS",   name: "Gujarat Gas" },
  { symbol: "HAL.NS",         name: "Hindustan Aeronautics" },
  { symbol: "HINDCOPPER.NS",  name: "Hindustan Copper" },
  { symbol: "HONASA.NS",      name: "Honasa Consumer (Mamaearth)" },
  { symbol: "ICICIGI.NS",     name: "ICICI Lombard General Insurance" },
  { symbol: "ICICIPRULI.NS",  name: "ICICI Prudential Life Insurance" },
  { symbol: "IDFCFIRSTB.NS",  name: "IDFC First Bank" },
  { symbol: "IGL.NS",         name: "Indraprastha Gas" },
  { symbol: "INDHOTEL.NS",    name: "Indian Hotels (Taj)" },
  { symbol: "INDIGO.NS",      name: "IndiGo (InterGlobe Aviation)" },
  { symbol: "INDIAMART.NS",   name: "IndiaMART InterMESH" },
  { symbol: "IPCALAB.NS",     name: "IPCA Laboratories" },
  { symbol: "IRB.NS",         name: "IRB Infrastructure" },
  { symbol: "IRCON.NS",       name: "IRCON International" },
  { symbol: "IREDA.NS",       name: "IREDA" },
  { symbol: "IRFC.NS",        name: "Indian Railway Finance Corporation" },
  { symbol: "JINDALSTEL.NS",  name: "Jindal Steel & Power" },
  { symbol: "JKLAKSHMI.NS",   name: "JK Lakshmi Cement" },
  { symbol: "JSWENERGY.NS",   name: "JSW Energy" },
  { symbol: "JUBLFOOD.NS",    name: "Jubilant FoodWorks (Domino's)" },
  { symbol: "KARURVYSYA.NS",  name: "Karur Vysya Bank" },
  { symbol: "KAVERI.NS",      name: "Kaveri Seed Company" },
  { symbol: "KEC.NS",         name: "KEC International" },
  { symbol: "KEI.NS",         name: "KEI Industries" },
  { symbol: "KPITTECH.NS",    name: "KPIT Technologies" },
  { symbol: "LAURUSLABS.NS",  name: "Laurus Labs" },
  { symbol: "LEMONTREE.NS",   name: "Lemon Tree Hotels" },
  { symbol: "LICHSGFIN.NS",   name: "LIC Housing Finance" },
  { symbol: "LICI.NS",        name: "Life Insurance Corporation of India" },
  { symbol: "M&MFIN.NS",      name: "Mahindra & Mahindra Financial Services" },
  { symbol: "MANAPPURAM.NS",  name: "Manappuram Finance" },
  { symbol: "MANYAVAR.NS",    name: "Vedant Fashions (Manyavar)" },
  { symbol: "MAXHEALTH.NS",   name: "Max Healthcare Institute" },
  { symbol: "MCX.NS",         name: "Multi Commodity Exchange" },
  { symbol: "MCDOWELL-N.NS",  name: "United Spirits" },
  { symbol: "MGL.NS",         name: "Mahanagar Gas" },
  { symbol: "MPHASIS.NS",     name: "Mphasis" },
  { symbol: "NATIONALUM.NS",  name: "National Aluminium" },
  { symbol: "NATCOPHARM.NS",  name: "Natco Pharma" },
  { symbol: "NAVINFLUOR.NS",  name: "Navin Fluorine International" },
  { symbol: "NCC.NS",         name: "NCC" },
  { symbol: "NHPC.NS",        name: "NHPC" },
  { symbol: "NIPPONLIFE.NS",  name: "Nippon India AMC" },
  { symbol: "NYKAA.NS",       name: "Nykaa (FSN E-Commerce)" },
  { symbol: "OBEROIRLTY.NS",  name: "Oberoi Realty" },
  { symbol: "OLECTRA.NS",     name: "Olectra Greentech" },
  { symbol: "PAYTM.NS",       name: "Paytm (One97 Communications)" },
  { symbol: "PERSISTENT.NS",  name: "Persistent Systems" },
  { symbol: "PETRONET.NS",    name: "Petronet LNG" },
  { symbol: "PFC.NS",         name: "Power Finance Corporation" },
  { symbol: "PFIZER.NS",      name: "Pfizer India" },
  { symbol: "PHOENIXLTD.NS",  name: "Phoenix Mills" },
  { symbol: "PNCINFRA.NS",    name: "PNC Infratech" },
  { symbol: "POLICYBZR.NS",   name: "PB Fintech (PolicyBazaar)" },
  { symbol: "PRESTIGE.NS",    name: "Prestige Estates" },
  { symbol: "RADICO.NS",      name: "Radico Khaitan" },
  { symbol: "RAMCOCEM.NS",    name: "Ramco Cements" },
  { symbol: "RBLBANK.NS",     name: "RBL Bank" },
  { symbol: "RECLTD.NS",      name: "REC Limited" },
  { symbol: "RITES.NS",       name: "RITES" },
  { symbol: "RVNL.NS",        name: "Rail Vikas Nigam" },
  { symbol: "SAPPHIRE.NS",    name: "Sapphire Foods India" },
  { symbol: "SJVN.NS",        name: "SJVN" },
  { symbol: "SOBHA.NS",       name: "Sobha" },
  { symbol: "SOLARINDS.NS",   name: "Solar Industries India" },
  { symbol: "SPICEJET.NS",    name: "SpiceJet" },
  { symbol: "STARHEALTH.NS",  name: "Star Health Insurance" },
  { symbol: "SUNTV.NS",       name: "Sun TV Network" },
  { symbol: "SUPREMEIND.NS",  name: "Supreme Industries" },
  { symbol: "TATACHEM.NS",    name: "Tata Chemicals" },
  { symbol: "TATAPOWER.NS",   name: "Tata Power" },
  { symbol: "THERMAX.NS",     name: "Thermax" },
  { symbol: "TIINDIA.NS",     name: "Tube Investments of India" },
  { symbol: "TORNTPOWER.NS",  name: "Torrent Power" },
  { symbol: "UBL.NS",         name: "United Breweries" },
  { symbol: "UJJIVANSFB.NS",  name: "Ujjivan Small Finance Bank" },
  { symbol: "UNIONBANK.NS",   name: "Union Bank of India" },
  { symbol: "VBL.NS",         name: "Varun Beverages" },
  { symbol: "VGUARD.NS",      name: "V-Guard Industries" },
  { symbol: "VOLTAS.NS",      name: "Voltas" },
  { symbol: "WELCORP.NS",     name: "Welspun Corp" },
  { symbol: "WESTLIFE.NS",    name: "Westlife Foodworld (McDonald's India)" },
  { symbol: "YESBANK.NS",     name: "Yes Bank" },
  { symbol: "ZEEL.NS",        name: "Zee Entertainment" },
  { symbol: "360ONE.NS",      name: "360 One WAM" },
  { symbol: "CDSL.NS",        name: "Central Depository Services" },
  { symbol: "AFFLE.NS",       name: "Affle India" },
  { symbol: "AMBER.NS",       name: "Amber Enterprises" },
  { symbol: "AMARARAJA.NS",   name: "Amara Raja Energy & Mobility" },
  { symbol: "BSOFT.NS",       name: "Birlasoft" },
  { symbol: "COROMANDEL.NS",  name: "Coromandel International" },
  { symbol: "EIH.NS",         name: "EIH (Oberoi Hotels)" },
  { symbol: "FINOLEX.NS",     name: "Finolex Cables" },
  { symbol: "FINPIPE.NS",     name: "Finolex Industries" },
  { symbol: "GNFC.NS",        name: "GNFC" },
  { symbol: "GODREJAGROVET.NS", name: "Godrej Agrovet" },
  { symbol: "GUJALKALI.NS",   name: "Gujarat Alkalies" },
  { symbol: "HEXAWARE.NS",    name: "Hexaware Technologies" },
  { symbol: "IDEA.NS",        name: "Vodafone Idea" },
  { symbol: "INDIANB.NS",     name: "Indian Bank" },
  { symbol: "IOB.NS",         name: "Indian Overseas Bank" },
  { symbol: "JYOTHYLAB.NS",   name: "Jyothy Labs" },
  { symbol: "KANSAINER.NS",   name: "Kansai Nerolac Paints" },
  { symbol: "MAHABANK.NS",    name: "Bank of Maharashtra" },
  { symbol: "MAHLOG.NS",      name: "Mahindra Logistics" },
  { symbol: "NETWORK18.NS",   name: "Network18 Media" },
  { symbol: "ORIENTELEC.NS",  name: "Orient Electric" },
  { symbol: "PCBL.NS",        name: "PCBL (Carbon Black)" },
  { symbol: "PNBHOUSING.NS",  name: "PNB Housing Finance" },
  { symbol: "PURVA.NS",       name: "Puravankara" },
  { symbol: "RALLIS.NS",      name: "Rallis India" },
  { symbol: "SANOFI.NS",      name: "Sanofi India" },
  { symbol: "SHRIRAMFIN.NS",  name: "Shriram Finance" },
  { symbol: "SUNDRMFAST.NS",  name: "Sundram Fasteners" },
  { symbol: "TANLA.NS",       name: "Tanla Platforms" },
  { symbol: "TATAELXSI.NS",   name: "Tata Elxsi" },
  { symbol: "UCOBANK.NS",     name: "UCO Bank" },
  { symbol: "VMART.NS",       name: "V-Mart Retail" },
  { symbol: "ABFRL.NS",       name: "Aditya Birla Fashion" },
  { symbol: "VARDHMAN.NS",    name: "Vardhman Textiles" },
  { symbol: "CENTRALBK.NS",   name: "Central Bank of India" },
  { symbol: "CHAMBLFERT.NS",  name: "Chambal Fertilisers" },
  { symbol: "SUNTECK.NS",     name: "Sunteck Realty" },
  { symbol: "SCHAEFFLER.NS",  name: "Schaeffler India" },
  { symbol: "BHARTIHEXA.NS",  name: "Bharti Hexacom" },
];
